language: java
jdk:
- oraclejdk7
install:
- "./gradlew clean"
script:
- FORGE_VERSION=1.10.2-12.18.3.2254 ./gradlew reobf
- FORGE_VERSION=1.11.2-13.20.0.2260 ./gradlew reobf
branches:
  only:
  - master
before_cache:
- rm -f $HOME/.gradle/caches/minecraft/de/oceanlabs/mcp/mcp_snapshot/20161228/.cache
- rm -f $HOME/.gradle/caches/minecraft/McpMappings.json*
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/fileHashes/
- rm -rf $HOME/.gradle/caches/minecraft/deobfedDeps/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag "dev-build-${TRAVIS_BUILD_NUMBER}" -a -m "Development Build ${TRAVIS_BUILD_NUMBER}"
- git push -q --tags
deploy:
  provider: releases
  skip_cleanup: true
  file: build/libs/*.jar
  file_glob: true
  prerelease: true
  on:
    tags: false
  api_key:
    secure: Z29G4EBjLhlxtzn4fxZwQZfE87KOSh0uLMAqfDe7whDDNztAIntq6SZJEo+zmH9+dBNYpYCFra+wm6tK9+Qt9DaOsLB5yX00Zia6tW5Z1BdruRamdVLoMNfWxcb2tULElMm8/OHVN9mij4q+czfZe3BugcWna66IkpJGJhcMz96dL/Exw3SHhseWnmlDNXC4zN8jM2jxMDaHgALaQOXkaa635eXwlhjuDKavUk4zClBKjODXX06fyuXEVLd9JFeOjCgOIYzRSTTG78Xzimj1cEBqekAw0J/SERvOCo2+jCr+Bzhrs1B0qekrPoWCI6ZXU7yB7v2xvxC2WZjF9y4s9c8zNihbLJulvHbdpAfoMSyvzzW2G/hOyurpF8MtcDgeJDY4U7fr0bJN1WJNPveJQRbamz8fIf+eYvoBQAvCEGGOOb8kd0ML8RfcVi4x29SDowDjPKUZ8nym8snDw/4VzwHrgENWUyw8CtfQ4oKIAPIN6uzKso9fvSO3oUGseEE9PYw8I9QQAux2+eQEFKm8uJ8yLp/93U1dk8wJqC5EHz3jXoUX0XSpMt0vrX+T0dgK7oAB4FkmpvfqwHcPWS0C+Dr0bYoS97gDsqe5arxIdV/XXtIayt9xZIvB1oF5Ffn9LnHwUp5QtDNfxWt16oX0uCkCavx152he/OD0Rj9qLcQ=
