language: java
jdk:
- oraclejdk7
install:
- "./gradlew clean"
script:
- FORGE_VERSION=1.10.2-12.18.3.2254 ./gradlew reobf
- FORGE_VERSION=1.11.2-13.20.0.2260 ./gradlew reobf
branches:
  only:
  - master
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/fileHashes/
- rm -rf $HOME/.gradle/caches/minecraft/deobfedDeps/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git tag -m "Development Build ${TRAVIS_BUILD_NUMBER}" "dev-build-${TRAVIS_BUILD_NUMBER}"
- git push -q ${GITHUB_REPO} --tags
deploy:
  provider: releases
  skip_cleanup: true
  file: build/libs/*.jar
  file_glob: true
  prerelease: true
  on:
    tags: false
  api_key:
    secure: s6SvLyw+jdw1YQueXFdSYN1kngDZ7qrN7F3dsE955mJnpT09YzuZPooU3V6JrZ76y2JnazvUbH1ym15xqtKshC0FI94LPH49Wva+wFwJ+Pwt71Tos3st2SWXjhuwh1P7RzUCP3heKz40cEGodkgM41O5X+BLJYOz68iFTdMPZE3zIMh7C8C9LDk1/Wb75eO92NHlBISu6cKLGvD5GW4pfPujk2+w4mvr3NkCJZdoLlQO17Fnh++Yu+dAzh2Gw/wnyPxrLXaQtNxQ1JM5KiiTVmrPf0GOBxwq7s3LZewYvNmrT5/308Q6UIzH/Dmw/4IYeD/FoE+d05jlAe3xAX3dtQgeTyztasZmMFoNhQxKQBgG6b2rcdFkbaWt6Z2y80C3zQbRKMWdpoYHYqAUnuj/w+z9ZItbwkQUUNkzRahGuX6QI8ZPkhCnpcIyyn0gpLWxHNy9qX1nHIee7jvdilXLPxtscRTFQd9exBlvhlhBVygVVO+rDQrYC/5wB42rr3UkUT9GrRRdNvGFohibYV9NLiJNrsjTNg2m2t8hbLMt2WRUVTivpK/Gsmla5dbfoECv3a9QcnlxfRR/igAunA5eDkzm7FPKj/+N16e6f14kKhqEJ5tHZBcn/SuRqxM7D4ttkLyVdJMj+tIP0f1qtVIz37obPF0rTM/EZX4bBPBYCks=
